// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsgqgemfszprfghkizqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzZ3FnZW1mc3pwcmZnaGtpenFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTQyMzAsImV4cCI6MjA3MTYzMDIzMH0.GPibs4lobbLzSW2zo81g8-lwwfRBKFX3NmOFvnv4K68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});